### ISSUE TITLE
ItemBinder.kt has list search in getItemViewType method that call very often

### ISSUE THREAD

**Issue by SSvistunov** [avito-tech/Konveyor#15]
So I think we can 
1. convert list to map and return view types from map 
or
2. add map for cache values and check cache before walking through list

I will do PR if no cons for my points.

**Comment by nesterov-n** [comment]
PR Would be great! 

But what do you plan to use as a map key?

**Comment by SSvistunov** [comment]
javaClass.name from item object

**Comment by nesterov-n** [comment]
But it is a breaking change? Some clients might execute tricky logic in `isRelevantItem` implementation. 
Example from real project: 
```
override fun isRelevantItem(item: Item): Boolean {
        return item is Message && item.body is BodyText
}
```

**Comment by SSvistunov** [comment]
yep, you absolutely right, it is breaking change
