### ISSUE TITLE
Move some abstraction to internal

### ISSUE THREAD

**Issue by philipuvarov** [avito-tech/Konveyor#5]
@bagza it looks like ViewTypeProvider and EmptyViewHolder can be internal. Could you check if we break anything by this?

**Comment by nesterov-n** [comment]
`EmptyViewHolder` is used. `ViewTypeProvider` can be internal. Will prepare PR

**Comment by nesterov-n** [comment]
`ViewTypeProvider` cannot be `internal`as it is part of signature if public `SimpleAdapterPresenter` constructor

@Kistamushken Should we close this issue?

**Comment by philipuvarov** [comment]
yeah, guess so
